
#General settings
[general]
	#24 hour or 12 hour format. (true: 24, false: 12)
	time_format = true
	#Show timestamp before text. (false: show after)
	show_before = true
	#Show seconds
	show_seconds = false
	#Use a different color for every player
	name_based = false
	#Show AM/PM
	#Requires TIME_FORMAT to be false
	show_period = false
	#Decimal color code
	#https://www.mathsisfun.com/hexadecimal-decimal-colors.html
	#Default: 11184810 (gray)
	#Range: 0 ~ 16777215
	color_code = 10010319

