#No comment
debug = false
#Mods listed here will be preferred during the unify process. Entries at the beginning have the highest priority.
modPriority = ["minecraft","thermal","mekanism"]
#Item tags which won't be unified. Useful when specifying a folder in 'tagsToUnify' but not all tags from that folder should be unified.
tagsToIgnore = []
#Item tags which will be unified. When leaving a '/' at the end that means that all tags inside that folder will be unified.
tagsToUnify = ["forge:dusts/", "forge:gems/", "forge:ingots/", "forge:nuggets/", "forge:ores/", "forge:rods/", "forge:storage_blocks/"]

